services:
  postgres:
    container_name: postgres
    image: postgres:16.8-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_USER=nakama
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nakama"]
      interval: 10s
      timeout: 5s
      retries: 5

  evr-bot:
    container_name: evr-bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - ./evr_servers.db:/app/evr_servers.db
    restart: always
    depends_on:
      - postgres

volumes:
  data:
